### ISSUE TITLE
Code provider?

### ISSUE THREAD

**Issue by Oleg26Dev** [twenzel/FlaUIRecorder#9]
<deleted>

**Comment by twenzel** [comment]
You have to build the FlaUIRecorder.CodeProvider.CSharp also. This builds and copies the common output folder.
This issue is already fixed in a private branch. Will be published soon.

**Comment by Oleg26Dev** [comment]
Thank you.
Another question: I have selected the c# as a code provider and created a file with scenario test.urp.
How to use it, how to replay it etc?
